<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Acer-ALG" failures="1" tests="10" name="com.example.tests.ui.UiTests" time="315.361" errors="0" timestamp="2025-09-10T20:14:14 IST" skipped="0">
  <testcase classname="com.example.tests.ui.UiTests" name="openBing" time="29.767"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openWikipedia" time="30.411"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openExampleDotCom" time="31.462"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openDomainDotCom" time="46.160"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openGithub_home" time="31.501"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openJsonPlaceholderHome" time="18.886"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openYahoo" time="37.271"/>
  <testcase classname="com.example.tests.ui.UiTests" name="navigateToAboutMozilla" time="15.705"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openGoogle_checkTitle" time="30.730"/>
  <testcase classname="com.example.tests.ui.UiTests" name="openStackOverflow" time="43.468">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.example.tests.ui.UiTests.openStackOverflow(UiTests.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
at java.base/java.lang.Thread.run(Thread.java:1447)
]]>
    </failure>
  </testcase> <!-- openStackOverflow -->
</testsuite> <!-- com.example.tests.ui.UiTests -->
